version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/React-app-docker-container
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_containers.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_containers.sh
      timeout: 300
      runas: ec2-user 